### ISSUE TITLE
multiple rviz gets launched while launching moveit

### ISSUE THREAD

**Issue by padhupradheep** [UniversalRobots/Universal_Robots_ROS2_Gazebo_Simulation#17]
the issue is in this [line](https://github.com/UniversalRobots/Universal_Robots_ROS2_Gazebo_Simulation/blob/708c48bfb10cb754728d4c856187579110d5342b/ur_simulation_gazebo/launch/ur_sim_control.launch.py#L118)

somehow the `Ifcondition()` is not taking in the value of the `LaunchConfiguration`. Maybe Open robotics changed something in the Python launch for Humble, which I might be unaware of. 

 As an alternate we need to use the `LaunchContext` to get the value of the `LaunchConfiguration`. 

Hope this helps!

**Comment by fmauch** [comment]
If what you're saying is that

```
ros2 launch ur_simulation_gazebo ur_sim_control.launch.py launch_rviz:=false
```

does start an RViz window on ROS2 Humble, I cannot confirm this.

**Comment by padhupradheep** [comment]
No, I meant that, when I tried to launch `ur_sim_moveit.launch.py` we have 2 RViz window opened.  

One from the [ur_sim_control.launch.py](https://github.com/UniversalRobots/Universal_Robots_ROS2_Gazebo_Simulation/blob/708c48bfb10cb754728d4c856187579110d5342b/ur_simulation_gazebo/launch/ur_sim_moveit.launch.py#L52)

second one is from [ur_config_moveit.launch.py](https://github.com/UniversalRobots/Universal_Robots_ROS2_Gazebo_Simulation/blob/708c48bfb10cb754728d4c856187579110d5342b/ur_simulation_gazebo/launch/ur_sim_moveit.launch.py#L68)

**Comment by fmauch** [comment]
Thanks for clarifying. Yes, that seems to be a problem, indeed. Looking at the galactic version the problem seems to exist there, as well.

**Comment by Icon45** [comment]
Has this Issue been fixed? I have a similar problem

**Comment by fmauch** [comment]
#44 adds a workaround (at least on my machine), but I don't quite understand why that happens in the first place / why it is resolved by this. Doesn't seem like a clean solution for the problem.

**Comment by padhupradheep** [comment]
I'd be working on a project with UR arms in next few days. I'll also analyze it a bit..
