### ISSUE TITLE
Process has dies with error message 

### ISSUE THREAD

**Issue by ghost** [UniversalRobots/Universal_Robots_ROS2_Gazebo_Simulation#27]
Hey, After the installation of simulation, and run codes `os2 launch ur_simulation_gazebo ur_sim_control.launch.py`, I have encountered with this error; `[ERROR] [gzserver-4]: process has died [pid 8997, exit code -11, cmd 'gzserver -slibgazebo_ros_init.so -slibgazebo_ros_factory.so -slibgazebo_ros_force_system.so']` 
Is this because source folder cannot recognize urdf file? I have installed ROS2 Driver, Description with Binary builds, but installed Simulation repo with source build.
Thanks in advance.

**Comment by fmauch** [comment]
Things like this can happen, if you are building packages inside your source workspace but have downstream packages installed from binary. E.g. I once had `ros2_control` built in my workspace, but had `gazebo_ros2_control` binary-installed.

I hope, this helps resolving this. As this post is rather old and should not be a problem in "normal" installations, I'll go ahead and close this. Please feel free to comment / reopen if the issue still persists for you.
