### ISSUE TITLE
Robot Movement Velocity

### ISSUE THREAD

**Issue by Icon45** [UniversalRobots/Universal_Robots_ROS2_Gazebo_Simulation#30]
Hi everyone,

i'm trying to set the movement speed of the ur in my simulation. Unfortunately i don't know how to do that since i'm only sending a joint trajectory to the respective topic. Does anyone know how to set the velocity so that the robot can move faster/slower than the default?

**Comment by fmauch** [comment]
The trajectory that you send for execution is being executed with the time constraints from that trajectory. If you want to execute that slower, you'll have to modify the trajectory. However, you can also reduce the real-time update rate of your simulation. The default is at `1000`, the following limits the RT-factor to 0.5:

![image](https://github.com/UniversalRobots/Universal_Robots_ROS2_Gazebo_Simulation/assets/491645/2d169bc9-2afa-4ff6-aea0-997e0368593f)

I hope, this helps, I'll close this as resolved. Feel free to reopen / comment if you think this is not justified.
