### ISSUE TITLE
Universal Robot Model in Gazebo

### ISSUE THREAD

**Issue by student-0103** [UniversalRobots/Universal_Robots_ROS2_Gazebo_Simulation#31]
Is it possible to spawn a Universal Robots model in Gazebo, like the UR5e?
I've got Ubuntu Desktop 22.04 LTS and ROS2 Humble.

**Comment by fmauch** [comment]
Yes, that should be possible. Please see the README, it has been updated recently. I'll go ahead and close this. Feel free to comment / reopen if you think, the question isn't answered.
