### ISSUE TITLE
UR5 not working correctly

### ISSUE THREAD

**Issue by fmauch** [UniversalRobots/Universal_Robots_ROS2_Gazebo_Simulation#34]
The UR5 seems not to be simulated correctly. It's the only robot that shakes directly after start. While with the others I can execute trajectories, with the UR5 this doesn't work.

**Comment by fmauch** [comment]
probably a duplicate of #11

**Comment by T-BonesLek** [comment]
Is there a workaround? Can we use the E-series model as a reference, or are the controls significantly different?

**Comment by RobertWilbrandt** [comment]
As of https://github.com/UniversalRobots/Universal_Robots_ROS2_Description/pull/127, this should no longer be an issue. I created #57 to remove the out-of-date note in the README.

**Comment by T-BonesLek** [comment]
@RobertWilbrandt I am new to this. Do I still need to use this repo and combine it with https://github.com/UniversalRobots/Universal_Robots_ROS2_Description repo ?

or is the ros2 Description a new "working" version of the gazebo simulation ?

probably wrong place to ask, but how do I include a custom gripper ? I have dae and STL files. the urdf is all in xacro formate, not the usual link and  Joint

**Comment by RobertWilbrandt** [comment]
This repo uses the robot models from `ur_robot_description` (see [here](https://github.com/UniversalRobots/Universal_Robots_ROS2_Gazebo_Simulation/blob/ros2/ur_simulation_gazebo/urdf/ur_gazebo.urdf.xacro#L6)). You don't have to do anything extra for this.

You would normally create a new description and simulation package for adding more external components to the arm. In the description you would instantiate the ur xacro macro and then add your custom urdf / xacro to it. We are currently working on a tutorial [here](https://github.com/UniversalRobots/Universal_Robots_ROS_Tutorials/pull/12), you can take a look if it is useful to you in its current form already.

Feel free to open a new issue if there are problems with this.
