### ISSUE TITLE
Adding one package to the .repos file

### ISSUE THREAD

**Issue by tonypg39** [UniversalRobots/Universal_Robots_ROS2_Gazebo_Simulation#51]
It happened to me that rosdep install was failing since I hadn't installed the `kinematics_interface` package, I added it to the .repos and it worked smoothly. The concrete error I was receiving was:

ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
admittance_controller: Cannot locate rosdep definition for [kinematics_interface_kdl]

Hope it helps!
Cheers

**Comment by VinDp** [comment]
Hey @tonypg39, 
thanks for the suggestion, but could it be that you were missing a ```rosdep update```?  Because we never experienced this kind of issue. So here there are some commands you can try for that (according to the distro you are using):

```
rosdep resolve kinematics_interface_kdl --rosdistro humble                                                                                                                                                                                                                                                             
#apt
ros-humble-kinematics-interface-kdl
```
```
rosdep resolve kinematics_interface_kdl --rosdistro iron                                                                                                                                                                                                                                                               
#apt
ros-iron-kinematics-interface-kdl
```

If this does not solve your problem, feel free to reopen or comment!
