### ISSUE TITLE
Keeps requiring ur_joint_control even though it doesnt come with it (ROS2 Humble)

### ISSUE THREAD

**Issue by Chillhopper** [UniversalRobots/Universal_Robots_ROS2_Gazebo_Simulation#61]
[INFO] [launch]: All log files can be found below /home/lusmse/.ros/log/2024-03-20-22-02-53-812384-lusmse-5237
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): executed command failed. Command: /opt/ros/humble/bin/xacro /home/lusmse/workspaces/ur_gazebo/install/ur_simulation_gazebo/share/ur_simulation_gazebo/urdf/ur_gazebo.urdf.xacro safety_limits:=true safety_pos_margin:=0.15 safety_k_position:=20 name:=ur ur_type:=ur5e prefix:="" simulation_controllers:=/home/lusmse/workspaces/ur_gazebo/install/ur_simulation_gazebo/share/ur_simulation_gazebo/config/ur_controllers.yaml
Captured stderr output: error: No such file or directory: /opt/ros/humble/share/ur_description/urdf/inc/ur_joint_control.xacro [Errno 2] No such file or directory: '/opt/ros/humble/share/ur_description/urdf/inc/ur_joint_control.xacro'
when processing file: /home/lusmse/workspaces/ur_gazebo/install/ur_simulation_gazebo/share/ur_simulation_gazebo/urdf/ur_gazebo.ros2_control.xacro
included from: /home/lusmse/workspaces/ur_gazebo/install/ur_simulation_gazebo/share/ur_simulation_gazebo/urdf/ur_gazebo.urdf.xacro

**Comment by RobertWilbrandt** [comment]
Please confirm that you are on the `humble` branch of the repo, the `urdf` files listed in the error message should only be required on the `ros2` branch.

If this is not the issue, you have to provide more information than just an error log:
- Which distribution are you on?
- Which packages do you build from sources and which are installed as binary packages?
- What specific commands did you run?
- Paste the full console output

**Comment by Chillhopper** [comment]
Yes it was a branch issue, thank you for your help. There is something I'd like to ask about your package. If I want to change the coordinates of the UR robot spawning as well the gazebo world it spawns in, where am i supposed to configure them?

**Comment by RobertWilbrandt** [comment]
In this case you would typically create your own description package which uses the `ur_robot` macro in `ur_description` and adds all further parts of your world model (in addition to positioning the robot as you like). You should then be able to use the [`description_package`](https://github.com/UniversalRobots/Universal_Robots_ROS2_Gazebo_Simulation/blob/humble/ur_simulation_gazebo/launch/ur_sim_control.launch.py#L56) launch parameter to load your custom description.

As your initial issue is fixed i'll close this, feel free to open a new issue if you have problems getting this running.
